### ISSUE TITLE
Using an ubuntu flavor memcache instance breaks the regex

### ISSUE THREAD

**Issue by johnkelly** [ktheory/dalli-elasticache#22]
https://github.com/ktheory/dalli-elasticache/blob/565bf94ed97812aa5b41ad71036b4f8b3c60c172/lib/dalli/elasticache/auto_discovery/stats_response.rb#L19 is:
STAT version 1.4.14 (Ubuntu)

Results in the error:
undefined method `[]' for nil:NilClass

Which was traced back to: 
https://github.com/ktheory/dalli-elasticache/blob/565bf94ed97812aa5b41ad71036b4f8b3c60c172/lib/dalli/elasticache/auto_discovery/stats_response.rb#L26

The string 'STAT version 1.4.14 (Ubuntu)' is causing the regex to return nil because it failed to find matches

**Comment by AmitPatel-BoTreeConsulting** [comment]
I am also facing same issue on Ubuntu 14.04

**Comment by petergoldstein** [comment]
@johnkelly @aaronlifton I know it's been a very long time since this was filed, but I'm trying to understand the issue.  So if you're still around and have context to share, that would be very helpful.

Does this refer to ElastiCache or some other clustering mechanism?  If the latter, what is it?

If this issue arose on ElastiCache, how does one get an "Ubuntu flavor" memcache instance?

**Comment by petergoldstein** [comment]
I'm still not clear on when one would encounter such a version string - a numeric version, followed by a space, followed by additional text (e.g. `(Ubuntu)`), but the changes here - https://github.com/ktheory/dalli-elasticache/pull/37 should allow the gem to properly parse out the version number.

**Comment by petergoldstein** [comment]
I'm still not clear on the situation in which this issue arises, but the gem is now more flexible in its handling of the version string as of version 1.0.0.  Thanks for filing the issue.  Closing.  Please reopen if you still see this problem on this version of the gem.
